<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataTables = [
            [
                'id' => 1,
                'title' => 'Sostener el cielo',
                'author' => 'Cixin Liu',
                'isbn' => 9788418037252,
                'publisher' => 'Nova',
                'publish_date' => '2021-09-09',
                'pages' => 392,
                'summary' => 'En Sostener el cielo, Cixin Liu nos lleva a través del tiempo y del espacio. De una comunidad rural en las montañas, donde unos estudiantes tienen que recurrir a la física para prevenir una invasión alienígena, a las minas de carbón de la región septentrional de China, en las que una nueva tecnología podría llegar a salvar vidas o a desatar un incendio que arderá durante siglos. De una época muy parecida a la nuestra, en la que ordenadores de supercuerdas predicen todos nuestros movimientos, a dentro de diez mil años, cuando la humanidad al fin haya conseguido empezar de cero. Y también hasta el mismísimo final del universo.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 2,
                'title' => 'El problema de los tres cuerpos',
                'author' => 'Cixin Liu',
                'isbn' => 9788466659734,
                'publisher' => 'Nova',
                'publish_date' => '2016-01-01',
                'pages' => 416,
                'summary' => 'El primer libro de la Trilogía de los Tres Cuerpos, el fenómeno editorial chino que ha conquistado al mundo. Premio Hugo 2015 a la mejor novela. MÁS DE 32 MILLONES DE EJEMPLARES VENDIDOS EN TODO EL MUNDO. «Las novelas de Cixin Liu son maravillosas. Las recomiendo muchísimo».José Manuel Nieves, Cuarto Milenio. «Un descubrimiento científico y filosófico único». George R. R. Martin «Increíblemente imaginativa». Barack Obama. El problema de los tres cuerpos es la primera novela no escrita originariamente en inglés galardonada con el premio Hugo, el Nobel del género de la ciencia ficción.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 3,
                'title' => 'Fundación',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497599245,
                'publisher' => 'Debolsillo',
                'publish_date' => '2014-01-01',
                'pages' => 561,
                'summary' => 'Sus investigaciones en el campo de la psicohistoria (las matemáticas aplicadas a las grandes aglomeraciones humanas] auguraban un desastre imposible de prevenir. El Imperio estaba condenado… Pero el Plan Seldon era una estrategia a largo plazo, destinada a minimizar las peores consecuencias del futuro que se avecinaba. Para ello se establecieron dos Fundaciones en ambos extremos de la galaxia.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 4,
                'title' => 'Sapiens de animales a dioses',
                'author' => 'Yuval Noah Harari',
                'isbn' => 9788499926223,
                'publisher' => 'Debate',
                'publish_date' => '2015-10-07',
                'pages' => 496,
                'summary' => 'Hace 70.000 años al menos seis especies de humanos habitaban la Tierra. Hoy solo queda una, la nuestra: Homo Sapiens. ¿Cómo logró imponerse en la lucha por la existencia? ¿Por qué nuestros ancestros recolectores se unieron para crear ciudades y reinos? ¿Cómo llegamos a creer en dioses, en naciones o en los derechos humanos, a confiar en el dinero, en los libros o en las leyes? ¿Cómo acabamos sometidos a la burocracia, a los horarios y al consumismo? ¿Y cómo será el mundo en los milenios venideros?',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 5,
                'title' => 'El bosque oscuro',
                'author' => 'Cixin Liu',
                'isbn' => 9788466660921,
                'publisher' => 'Nova',
                'publish_date' => '2017-01-01',
                'pages' => 576,
                'summary' => 'Ahora la Tierra tiene cuatro siglos para defenderse de lo inevitable: la llegada de los Trisolaris. Los colaboracionistas humanos pueden haber sido derrotados, pero los sofones permiten a los extraterrestres acceder a la información de la humanidad, dejando al descubierto toda estrategia de defensa. Solo la mente humana sigue siendo un secreto, y ahora también la clave del acuciante plan que urdirán tres estadistas, un científico y un sociólogo.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 6,
                'title' => 'El fin de la muerte',
                'author' => 'Cixin Liu',
                'isbn' => 9788417347017,
                'publisher' => 'Nova',
                'publish_date' => '2018-01-01',
                'pages' => 736,
                'summary' => 'El desenlace de la magistral trilogía de ciencia ficción con 4 millones de lectores en China, convertida en un best seller de The New York Times y de Spiegel. Tras El problema de los tres cuerpos y El bosque oscuro, la tensa espera de la humanidad concluye ahora con un último episodio, tan extraordinario como los anteriores, lleno de ideas electrizantes y una calidad de obra maestra.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 7,
                'title' => 'La tierra errante',
                'author' => 'Cixin Liu',
                'isbn' => 9788417347567,
                'publisher' => 'Nova',
                'publish_date' => '2019-09-19',
                'pages' => 400,
                'summary' => 'El sol se está muriendo, y la Tierra, consumida por los últimos suspiros de esta estrella, también desaparecerá. Pero la humanidad, en lugar de abandonar el planeta, construye doce mil grandiosos motores de fusión para desorbitar la Tierra y propulsarla hacia Próxima Centauri en un viaje que durará siglos...',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 8,
                'title' => 'La esfera luminosa',
                'author' => 'Cixin Liu',
                'isbn' => 9788417347338,
                'publisher' => 'Nova',
                'publish_date' => '2019-03-21',
                'pages' => 464,
                'summary' => 'El día en que cumple catorce años, Chen presencia cómo una esfera luminosa entra en su casa y calcina a sus padres. Con el propósito de encontrar algún sentido a esta extraña desgracia, decide dedicarse a descifrar el secreto del misterioso fenómeno a causa del cual quedó huérfano. La búsqueda de la esfera luminosa lo llevará lejos de casa, a perseguir tormentas en las cimas de montañas y a adentrarse en laboratorios subterráneos secretos para, poco a poco, ir descubriendo nuevos límites en la física de partículas.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 9,
                'title' => 'La era de la supernova',
                'author' => 'Cixin Liu',
                'isbn' => 9788417347949,
                'publisher' => 'Nova',
                'publish_date' => '2020-10-15',
                'pages' => 496,
                'summary' => 'Hace ocho años y a ocho años luz de distancia, murió una estrella. Esta noche, una supernova de alta energía finalmente llegará a la Tierra. El cielo brillará cuando esa nueva estrella florezca y, dentro de un año, todos los adultos mayores de trece años estarán muertos. Sus cromosomas habrán quedado irreversiblemente dañados.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 10,
                'title' => 'Nemesis',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497934350,
                'publisher' => 'Debolsillo',
                'publish_date' => '2005-04-07',
                'pages' => 464,
                'summary' => 'Año 2236. La Tierra y su centenar de colinas espaciales están superpobladas, llevan una vida anárquica y socialmente degenerada. A dos años luz de distancia, oculta en un rincón de la galaxia, brilla una estrella parecida al Sol de la Tierra, una estrella que posee su propio sistema planetario: Megas, Erythro y Rotor, una colonia renegada de la Tierra. La estrella se llama Némesis y al ser descubierta es considerada como la última esperanza de la raza humana, un nuevo punto de partida para un valiente grupo de aventureros dirigidos por Januss Pitt, un individuo brillante pero megalómano.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 11,
                'title' => 'Viaje alucinante',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497931410,
                'publisher' => 'Debolsillo',
                'publish_date' => '2004-01-07',
                'pages' => 240,
                'summary' => 'Un eminente sabio, víctima de un intento de asesinato, yace en estado comatoso a causa de un coágulo cerebral. En su mente lleva un secreto de extraordinaria importancia para la supervivencia del mundo libre. Una operación significaría su muerte. Entonces, un grupo de sabios resuelve miniaturizar a un equipo de médicos y técnicos, con todos sus aparatos, e inyectarlo en el sistema circulatorio del enfermo... Próxima parada: el cerebro.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 12,
                'title' => 'El fin de la eternidad',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497933537,
                'publisher' => 'Debolsillo',
                'publish_date' => '2004-07-09',
                'pages' => 288,
                'summary' => 'En el siglo XXVII, la Tierra funda una organización llamada Eternidad, enviando sus emisarios al pasado y al futuro para abrir el comercio entre las diferentes épocas, y para alterar la larga y a veces trágica historia de la raza humana. El proyecto estaba integrado sólo por los mejores y más brillantes exponentes de cada siglo: personas que dejaron de lado sus propias vidas para dedicarse a servir a los demás.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 13,
                'title' => 'Los propios dioses',
                'author' => 'Isaac Asimov',
                'isbn' => 9788499895352,
                'publisher' => 'Debolsillo',
                'publish_date' => '2011-09-01',
                'pages' => 344,
                'summary' => 'Los habitantes de un universo paralelo en el futuro, con leyes físicas ligeramente distintas a las nuestras, descubren la forma de intercambiar materia con nosotros. Materia que, una vez en el universo de destino, y merced a las diferencias físicas entre ambos, comienza a desprender energía de forma espontánea. Una vez consumida la capacidad energética del material, éste puede volver a ser intercambiado, para recomenzar el ciclo. ¿Qué podríamos hacer con un suministro de energía gratuita e inagotable?',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 14,
                'title' => 'Los Límites De La Fundación',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497594349,
                'publisher' => 'Debolsillo',
                'publish_date' => '2014-10-07',
                'pages' => 523,
                'summary' => 'Golan Trevize, consejero de la Primera Fundación, se pregunta sobre la posibilidad de la supervivencia de la Segunda Fundación. Esta debería haber sido destruida, según la versión oficial, agotándose así los súper poderes mentales de los científicos que la componían y que dirigían ocultamente los aconteceres del Imperio Galáctico.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 15,
                'title' => 'Trilogía De La Fundación',
                'author' => 'Isaac Asimov',
                'isbn' => 9788499083209,
                'publisher' => 'Debolsillo',
                'publish_date' => '2015-01-01',
                'pages' => 899,
                'summary' => 'La trilogía de la fundación está considerada la mejor serie de la ciencia ficción universal. Como tal, fue galardonada en 1966 con un premio Hugo, y ahora Debolsillo la presenta reunida en un único volumen: una lectura imprescindible para los amantes del género.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 16,
                'title' => 'Cuentos Completos 1',
                'author' => 'Isaac Asimov',
                'isbn' => 9789585579460,
                'publisher' => 'Debolsillo',
                'publish_date' => '2020-01-01',
                'pages' => 820,
                'summary' => 'Este primer tomo de la colección completa de cuentos cortos de Isaac Asimov contiene cuarenta y seis títulos, algunos de los cuales ya se han convertido en clásicos del género de la ciencia ficción.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 17,
                'title' => 'Cuentos Completos 2',
                'author' => 'Isaac Asimov',
                'isbn' => 9788466348409,
                'publisher' => 'Debolsillo',
                'publish_date' => '2021-10-07',
                'pages' => 736,
                'summary' => '¡Listos para otra dosis de ciencia ficción deslumbrante con “Cuentos Completos II” de Isaac Asimov! En este volumen, Asimov nos lleva a través de un laberinto de ideas futuristas y dilemas éticos que desafían nuestra percepción del universo. Desde relatos de robots con conciencia propia hasta encuentros cercanos con extraterrestres, cada cuento es una aventura emocionante que te dejará con la mente en órbita.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 18,
                'title' => 'Hacia la fundación',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497597692,
                'publisher' => 'Debolsillo',
                'publish_date' => '2003-06-27',
                'pages' => 448,
                'summary' => 'Hacia la Fundación es el segundo libro del "Ciclo de la Fundación", tercer bloque de la celebre "Saga de la Fundación" de Isaac Asimov, una portentosa saga que constituye una extraordinaria visión del futuro y que abarca miles de años y docenas de mundos.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 19,
                'title' => 'La redención del tiempo',
                'author' => 'Baoshu',
                'isbn' => 9788417347345,
                'publisher' => 'Nova',
                'publish_date' => '2018-10-18',
                'pages' => 368,
                'summary' => 'Al final del cuarto año de la Era de la Crisis, YunTianming, enfermo de cáncer, decide acabar con su vida. Esta decisión es el principio de un viaje hasta el final del universo. Congelan su cerebro y lo suben abordo de una nave espacial lanzada para interceptar a los trisolarianos. Se trata de un plan desesperado, casi condenado al fracaso, y las posibilidades de que un día Tianming pueda mandar información valiosa a la Tierra son mínimas. Sin embargo, contra todo pronóstico, lo consigue, y sus transmisiones revelan valiosos secretos para la única defensa posible desde la Tierra.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 20,
                'title' => 'El sol desnudo',
                'author' => 'Isaac Asimov',
                'isbn' => 8497937856,
                'publisher' => 'Debolsillo',
                'publish_date' => '2023-03-17',
                'pages' => 288,
                'summary' => 'Isaac Asimov es uno de los grandes maestros de la ciencia ficción del siglo XX. Autor de trayectoria legendaria, publicó más de quinientas obras, entre ellas la Trilogía Fundación -galardonada con los premios Hugo y Nebula-, Los propios dioses y El hombre bicentenario. Nacido en 1920 en Petróvichi, Rusia, siendo muy pequeño se trasladó con su familia a Estados Unidos y creció en la ciudad de Nueva York. Estudió en la Universidad de Columbia, donde se doctoró en Bioquímica. Mientras completaba sus estudios, sirvió como investigador en la Marina estadounidense durante la Segunda Guerra Mundial. ',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 21,
                'title' => 'Fundación y tierra',
                'author' => 'Isaac Asimov',
                'isbn' => 9788497599221,
                'publisher' => 'Debolsillo',
                'publish_date' => '2003-10-13',
                'pages' => 528,
                'summary' => 'Fundación y Tierra cierra argumentalmente el «Ciclo de la Fundación», así como la secuela a la grandiosa «Trilogía de la Fundación», y constituye una novela soberbia en la que vemos cómo la Humanidad, en un lejano futuro galáctico, busca sus orígenes en un planeta perdido llamado Tierra.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 22,
                'title' => 'Los límites de la Fundación',
                'author' => 'Isaac Asimov',
                'isbn' => 8497594347,
                'publisher' => 'Debolsillo',
                'publish_date' => '2003-02-17',
                'pages' => 528,
                'summary' => 'Los límites de la Fundación, sexto libro del «Ciclo de la Fundación», es la continuación de la «Trilogía de la Fundación» o «Ciclo de Trántor», la obra maestra de la ciencia ficción de Isaac Asimov.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ],
            [
                'id' => 23,
                'title' => 'Sueños de robot',
                'author' => 'Isaac Asimov',
                'isbn' => 8497931378,
                'publisher' => 'Debolsillo',
                'publish_date' => '2004-02-07',
                'pages' => 496,
                'summary' => '¿Cómo influirán los robots en la vida de la humanidad? ¿Qué papel desempeñarán en un futuro más o menos lejano estos extraños mecanismos creados por el hombre casi a su imagen y semejanza? Isaac Asimov nos brinda aquí unas narraciones que, sin lugar a dudas, moverán a reflexión. Las historias aparecen espléndidamente ilustradas por Ralph McQuarrie, diseñador de numerosas películas de ciencia ficción.',
                'created_at' => '2025-11-20 01:00:00',
                'updated_at' => '2025-11-20 01:00:00',
            ]
        ];
        
        DB::table("books")->insert($dataTables);
    }
}