<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataTables = [
            [
                'id' => 1,
                'id_user' => 1,
                'id_book' => 5,
                'add_date' => '2025-12-27 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 2,
                'id_user' => 3,
                'id_book' => 1,
                'add_date' => '2025-11-28 01:10:02',
                'read_date' => NULL,
                'comment' => 'EStá bastante bien!!',
                'rating' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 3,
                'id_user' => 4,
                'id_book' => 2,
                'add_date' => '2025-10-27 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 4,
                'id_user' => 1,
                'id_book' => 6,
                'add_date' => '2025-11-26 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 5,
                'id_user' => 2,
                'id_book' => 1,
                'add_date' => '2025-09-28 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 6,
                'id_user' => 2,
                'id_book' => 10,
                'add_date' => '2025-11-25 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 7,
                'id_user' => 1,
                'id_book' => 15,
                'add_date' => '2025-08-28 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 8,
                'id_user' => 3,
                'id_book' => 2,
                'add_date' => '2025-11-24 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 9,
                'id_user' => 2,
                'id_book' => 5,
                'add_date' => '2025-07-28 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 10,
                'id_user' => 1,
                'id_book' => 12,
                'add_date' => '2025-11-23 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 11,
                'id_user' => 2,
                'id_book' => 7,
                'add_date' => '2025-06-28 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 12,
                'id_user' => 4,
                'id_book' => 17,
                'add_date' => '2025-11-22 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 13,
                'id_user' => 4,
                'id_book' => 14,
                'add_date' => '2025-05-28 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 14,
                'id_user' => 1,
                'id_book' => 3,
                'add_date' => '2025-11-21 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 15,
                'id_user' => 3,
                'id_book' => 11,
                'add_date' => '2025-04-29 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 16,
                'id_user' => 2,
                'id_book' => 14,
                'add_date' => '2025-11-20 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 17,
                'id_user' => 1,
                'id_book' => 10,
                'add_date' => '2025-03-20 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 18,
                'id_user' => 4,
                'id_book' => 12,
                'add_date' => '2025-11-19 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 19,
                'id_user' => 3,
                'id_book' => 13,
                'add_date' => '2025-02-10 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 20,
                'id_user' => 2,
                'id_book' => 15,
                'add_date' => '2025-11-18 01:10:02',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ]
        ];
        
        DB::table("reviews")->insert($dataTables);
    }
}